import {getChatGPTUser} from '@/app/chatgpt-auth';
import {env} from 'cloudflare:workers';
import {Chess} from 'chess.js';
type Room={id:string;name:string;owner:string;elo:number;pgn:string;version:number;status:string};
function db(){if(!env.DB)throw new Error('Database is unavailable');return env.DB}
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function getRoom(id:string){const r=await db().prepare('SELECT * FROM rooms WHERE id=?').bind(id).first<Room>();if(!r)return null;const members=await db().prepare('SELECT user_id AS id,name FROM members WHERE room_id=?').bind(id).all();return {...r,members:members.results}}
async function isMember(id:string,user:string){return !!await db().prepare('SELECT 1 FROM members WHERE room_id=? AND user_id=?').bind(id,user).first()}
export async function GET(req:Request){try{const user=await getChatGPTUser();if(!user)return reply({error:'Please sign in first.'},401);const id=new URL(req.url).searchParams.get('id');if(id){if(!await isMember(id,user.userId))return reply({error:'Join this group before opening its board.'},403);return reply({room:await getRoom(id)})}const rows=await db().prepare('SELECT r.* FROM rooms r JOIN members m ON m.room_id=r.id WHERE m.user_id=? ORDER BY r.name').bind(user.userId).all();return reply({rooms:rows.results})}catch(e){console.error(e);return reply({error:'Your groups could not be loaded. Please try again.'},503)}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return reply({error:'Please sign in first.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return reply({error:'Invalid request origin.'},403);let body;try{body=await req.json() as Record<string,unknown>}catch{return reply({error:'Invalid request.'},400)}const {action}=body;let id=typeof body.id==='string'?body.id:'';const display=user.fullName||user.email.split('@')[0];
if(action==='create'){const name=typeof body.name==='string'?body.name.trim():'';const elo=Number(body.elo);if(!name||name.length>48||!Number.isInteger(elo)||elo<1320||elo>2400)return reply({error:'Choose a name and an Elo between 1320 and 2400.'},400);id=crypto.randomUUID();await db().batch([db().prepare('INSERT INTO rooms(id,name,owner,elo) VALUES(?,?,?,?)').bind(id,name,user.userId,elo),db().prepare('INSERT INTO members(room_id,user_id,name) VALUES(?,?,?)').bind(id,user.userId,display)]);return reply({room:await getRoom(id)})}
if(action==='join'){if(!id||id.length>100||!await getRoom(id))return reply({error:'That invite could not be found. Check the link and try again.'},404);await db().prepare('INSERT INTO members(room_id,user_id,name) VALUES(?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET name=excluded.name').bind(id,user.userId,display).run();return reply({room:await getRoom(id)})}
if(!await isMember(id,user.userId))return reply({error:'You are not a member of this group.'},403);const room=await getRoom(id);if(!room)return reply({error:'Group not found.'},404);if(body.version!==room.version)return reply({error:'The board changed. Your group’s latest move has been loaded.'},409);
let pgn=room.pgn,status=room.status,elo=room.elo;
if(action==='start'){if(room.owner!==user.userId)return reply({error:'Only the host can start a new game.'},403);if(status==='playing')return reply({error:'Finish the current game first.'},409);elo=Number(body.elo);if(!Number.isInteger(elo)||elo<1320||elo>2400)return reply({error:'Choose an Elo between 1320 and 2400.'},400);pgn='';status='playing'}
else if(action==='finish'){if(room.owner!==user.userId)return reply({error:'Only the host can finish the game.'},403);status='finished'}
else if(action==='move'){if(status!=='playing')return reply({error:'Start a game first.'},400);const game=new Chess();if(pgn)game.loadPgn(pgn);if(game.isGameOver())return reply({error:'This game is over.'},400);if((game.turn()==='b')!==(body.bot===true))return reply({error:'Wait for your team’s turn.'},400);try{game.move({from:String(body.from),to:String(body.to),promotion:typeof body.promotion==='string'?body.promotion:'q'})}catch{return reply({error:'That move is not legal.'},400)}pgn=game.pgn();if(game.isGameOver())status='finished'}else return reply({error:'Unknown action.'},400);
const updated=await db().prepare('UPDATE rooms SET pgn=?,status=?,elo=?,version=version+1 WHERE id=? AND version=?').bind(pgn,status,elo,id,room.version).run();if(!updated.meta.changes)return reply({error:'Another teammate moved first. The board has been refreshed.'},409);return reply({room:await getRoom(id)});
}catch(e){console.error(e);return reply({error:'Could not save your game. Please try again.'},503)}}
